AllCops:
  Include:
    - '**/Rakefile'
  Exclude:
    - 'spec/bdd/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false
